### ISSUE TITLE
 'DocTestBuilder' object has no attribute 'warn'

### ISSUE THREAD

**Issue by KPrasch** [aafigure/aafigure#3]
Hello - Thanks for your sphinx integration!

I have the following source RST that I want to render with your sphinx extension:

```
            stake
            ^
            |
         800|     +----+
            |     | 3rd|
         700+-----+----+
            |          |
         600|    2nd   +-------------+
            |          |     3rd     |
         500+----------+-------------+----------+
            |                                   |
            |               1st                 |
            |                                   |   period
            +-----------------------------------+--->	
```

I expect a rendered chart, but instead get the following error when running `sphinx==3.0.2`:

```
reading sources... [ 50%] architecture/slashing                                                                                                  
Exception occurred:
  File "/home/k/.local/share/virtualenvs/nucypher-iNjwDRsw/lib/python3.8/site-packages/aafigure/sphinxext.py", line 136, in render_aafig_images
    app.builder.warn(
AttributeError: 'DocTestBuilder' object has no attribute 'warn'
The full traceback has been saved in /tmp/sphinx-err-n9q_ybdd.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Makefile:19: recipe for target 'doctest' failed
make[1]: *** [doctest] Error 2
make[1]: Leaving directory '/home/k/Git/nucypher/docs'
Makefile:30: recipe for target 'build-docs' failed
make: *** [build-docs] Error 2
(nucypher) k@nova:~/Git/nucypher$ cat The full traceback has been saved in /tmp/sphinx-err-n9q_ybdd.log
cat: The: No such file or directory
cat: full: No such file or directory
cat: traceback: No such file or directory
cat: has: No such file or directory
cat: been: No such file or directory
cat: saved: No such file or directory
cat: in: No such file or directory
# Sphinx version: 3.0.1
# Python version: 3.8.0 (CPython)
# Docutils version: 0.16 release
# Jinja2 version: 3.0.0a1
# Last messages:
#   Running Sphinx v3.0.1
#   making output directory...
#   done
#   loading pickled environment...
#   done
#   building [mo]: targets for 0 po files that are out of date
#   building [doctest]: targets for 48 source files that are out of date
#   updating environment:
#   0 added, 2 changed, 0 removed
#   reading sources... [ 50%] architecture/slashing
# Loaded extensions:
#   sphinx.ext.mathjax (3.0.1) from /home/k/.local/share/virtualenvs/nucypher-iNjwDRsw/lib/python3.8/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from /home/k/.local/share/virtualenvs/nucypher-iNjwDRsw/lib/python3.8/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.2) from /home/k/.local/share/virtualenvs/nucypher-iNjwDRsw/lib/python3.8/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (1.0.3) from /home/k/.local/share/virtualenvs/nucypher-iNjwDRsw/lib/python3.8/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.4) from /home/k/.local/share/virtualenvs/nucypher-iNjwDRsw/lib/python3.8/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.3) from /home/k/.local/share/virtualenvs/nucypher-iNjwDRsw/lib/python3.8/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /home/k/.local/share/virtualenvs/nucypher-iNjwDRsw/lib/python3.8/site-packages/alabaster/__init__.py
#   sphinx.ext.autodoc.type_comment (3.0.1) from /home/k/.local/share/virtualenvs/nucypher-iNjwDRsw/lib/python3.8/site-packages/sphinx/ext/autodoc/type_comment.py
#   sphinx.ext.autodoc (3.0.1) from /home/k/.local/share/virtualenvs/nucypher-iNjwDRsw/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinx.ext.napoleon (3.0.1) from /home/k/.local/share/virtualenvs/nucypher-iNjwDRsw/lib/python3.8/site-packages/sphinx/ext/napoleon/__init__.py
#   sphinx.ext.intersphinx (3.0.1) from /home/k/.local/share/virtualenvs/nucypher-iNjwDRsw/lib/python3.8/site-packages/sphinx/ext/intersphinx.py
#   sphinx.ext.doctest (3.0.1) from /home/k/.local/share/virtualenvs/nucypher-iNjwDRsw/lib/python3.8/site-packages/sphinx/ext/doctest.py
#   aafigure.sphinxext (unknown version) from /home/k/.local/share/virtualenvs/nucypher-iNjwDRsw/lib/python3.8/site-packages/aafigure/sphinxext.py
Traceback (most recent call last):
  File "/home/k/.local/share/virtualenvs/nucypher-iNjwDRsw/lib/python3.8/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/home/k/.local/share/virtualenvs/nucypher-iNjwDRsw/lib/python3.8/site-packages/sphinx/application.py", line 348, in build
    self.builder.build_update()
  File "/home/k/.local/share/virtualenvs/nucypher-iNjwDRsw/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 297, in build_update
    self.build(to_build,
  File "/home/k/.local/share/virtualenvs/nucypher-iNjwDRsw/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 311, in build
    updated_docnames = set(self.read())
  File "/home/k/.local/share/virtualenvs/nucypher-iNjwDRsw/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 418, in read
    self._read_serial(docnames)
  File "/home/k/.local/share/virtualenvs/nucypher-iNjwDRsw/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 439, in _read_serial
    self.read_doc(docname)
  File "/home/k/.local/share/virtualenvs/nucypher-iNjwDRsw/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 479, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/home/k/.local/share/virtualenvs/nucypher-iNjwDRsw/lib/python3.8/site-packages/sphinx/io.py", line 221, in read_doc
    pub.publish()
  File "/home/k/.local/share/virtualenvs/nucypher-iNjwDRsw/lib/python3.8/site-packages/docutils/core.py", line 219, in publish
    self.apply_transforms()
  File "/home/k/.local/share/virtualenvs/nucypher-iNjwDRsw/lib/python3.8/site-packages/docutils/core.py", line 200, in apply_transforms
    self.document.transformer.apply_transforms()
  File "/home/k/.local/share/virtualenvs/nucypher-iNjwDRsw/lib/python3.8/site-packages/sphinx/transforms/__init__.py", line 86, in apply_transforms
    super().apply_transforms()
  File "/home/k/.local/share/virtualenvs/nucypher-iNjwDRsw/lib/python3.8/site-packages/docutils/transforms/__init__.py", line 171, in apply_transforms
    transform.apply(**kwargs)
  File "/home/k/.local/share/virtualenvs/nucypher-iNjwDRsw/lib/python3.8/site-packages/sphinx/transforms/__init__.py", line 376, in apply
    self.app.emit('doctree-read', self.document)
  File "/home/k/.local/share/virtualenvs/nucypher-iNjwDRsw/lib/python3.8/site-packages/sphinx/application.py", line 445, in emit
    return self.events.emit(event, *args)
  File "/home/k/.local/share/virtualenvs/nucypher-iNjwDRsw/lib/python3.8/site-packages/sphinx/events.py", line 107, in emit
    results.append(listener.handler(self.app, *args))
  File "/home/k/.local/share/virtualenvs/nucypher-iNjwDRsw/lib/python3.8/site-packages/aafigure/sphinxext.py", line 136, in render_aafig_images
    app.builder.warn(
AttributeError: 'DocTestBuilder' object has no attribute 'warn'

```

Any Idea what I might do as a workaround other then pre-rendering images with the `aafigure` CLI?

Thanks ahead of time for looking! :-)

**Comment by 0x8000-0000** [comment]
This might be similar to https://github.com/sphinx-contrib/aafig/issues/4 ?
