### ISSUE TITLE
0.6: documentation build fails on generate man page

### ISSUE THREAD

**Issue by kloczek** [aafigure/aafigure#5]
Looks like sometning is wrong with `aafigure` because it is not possible to generate documentation as man page and sphinx fails in `aafigure` code
<details>

```console
[tkloczko@pers-jacek aafigure-0.6]$ /usr/bin/sphinx-build -n -T -b man documentation build/sphinx/man
Running Sphinx v6.1.3
WARNING: html_static_path entry '_static' does not exist
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
writing output...
building [man]: all manpages
updating environment: 0 added, 3 changed, 0 removed
reading sources... [ 33%] examples
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/events.py", line 96, in emit
    results.append(listener.handler(self.app, *args))
  File "/home/tkloczko/rpmbuild/BUILD/aafigure-0.6/aafigure/sphinxext.py", line 136, in render_aafig_images
    app.builder.warn(
AttributeError: 'ManualPageBuilder' object has no attribute 'warn'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 284, in build_main
    app.build(args.force_all, args.filenames)
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 347, in build
    self.builder.build_update()
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 308, in build_update
    self.build(['__all__'], to_build)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 327, in build
    updated_docnames = set(self.read())
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 434, in read
    self._read_serial(docnames)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 455, in _read_serial
    self.read_doc(docname)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 511, in read_doc
    publisher.publish()
  File "/usr/lib/python3.8/site-packages/docutils/core.py", line 226, in publish
    self.apply_transforms()
  File "/usr/lib/python3.8/site-packages/docutils/core.py", line 206, in apply_transforms
    self.document.transformer.apply_transforms()
  File "/usr/lib/python3.8/site-packages/sphinx/transforms/__init__.py", line 80, in apply_transforms
    super().apply_transforms()
  File "/usr/lib/python3.8/site-packages/docutils/transforms/__init__.py", line 173, in apply_transforms
    transform.apply(**kwargs)
  File "/usr/lib/python3.8/site-packages/sphinx/transforms/__init__.py", line 359, in apply
    self.app.emit('doctree-read', self.document)
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 458, in emit
    return self.events.emit(event, *args, allowed_exceptions=allowed_exceptions)
  File "/usr/lib/python3.8/site-packages/sphinx/events.py", line 107, in emit
    raise ExtensionError(__("Handler %r for event %r threw an exception") %
sphinx.errors.ExtensionError: Handler <function render_aafig_images at 0x7f3895c63700> for event 'doctree-read' threw an exception (exception: 'ManualPageBuilder' object has no attribute 'warn')

Extension error (aafigure.sphinxext):
```
</details>

**Comment by kloczek** [comment]
BTW on generate html sphinx shows some warnings
<details>

```console
[tkloczko@pers-jacek aafigure-0.6]$ /usr/bin/sphinx-build -n -T -b html documentation build/sphinx/man
Running Sphinx v6.1.3
WARNING: html_static_path entry '_static' does not exist
building [mo]: targets for 0 po files that are out of date
writing output...
building [html]: targets for 9 source files that are out of date
updating environment: [new config] 9 added, 0 changed, 0 removed
reading sources... [100%] sphinxext
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] sphinxext
/home/tkloczko/rpmbuild/BUILD/aafigure-0.6/documentation/appendix.rst:113: WARNING: py:func reference target not found: process
/home/tkloczko/rpmbuild/BUILD/aafigure-0.6/documentation/appendix.rst:1: WARNING: py:class reference target not found: AsciiArtImage
/home/tkloczko/rpmbuild/BUILD/aafigure-0.6/documentation/appendix.rst:4: WARNING: py:func reference target not found: process
generating indices... genindex py-modindex done
writing additional pages... search done
copying static files... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded, 4 warnings.
```
</details>

You can peak on fixes that kind of issues in other projects
https://github.com/RDFLib/rdflib-sqlalchemy/issues/95
https://github.com/RDFLib/rdflib/pull/2036
https://github.com/click-contrib/sphinx-click/commit/abc31069
https://github.com/frostming/unearth/issues/14
https://github.com/jaraco/cssutils/issues/21
https://github.com/latchset/jwcrypto/pull/289
https://github.com/latchset/jwcrypto/pull/289
https://github.com/pypa/distlib/commit/98b9b89f
https://github.com/pywbem/pywbem/pull/2895
https://github.com/sissaschool/elementpath/commit/bf869d9e

**Comment by kloczek** [comment]
gentle ping .. any update? 🤔
